# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Internal function for `tidy(<skksph_paistr>)`
#'
#' @param pai hand
#' @returns list of integers
#' @keywords internal
skksph_tidy_impl <- function(pai) {
    .Call(`_shikakusphere_skksph_tidy_impl`, pai)
}

#' Internal function to lipai
#'
#' @param x list of characters
#' @returns list of hands
#' @keywords internal
skksph_lipai_impl <- function(x) {
    .Call(`_shikakusphere_skksph_lipai_impl`, x)
}

#' Internal function to convert hand to SVG
#'
#' @param pai hand
#' @returns SVG strings
#' @keywords internal
skksph_hand_to_svg <- function(pai) {
    .Call(`_shikakusphere_skksph_hand_to_svg`, pai)
}

#' Internal function to get defen
#'
#' @param paistr hand
#' @param baopai baopai
#' @param libaopai libaopai
#' @param list rule set
#' @param rankPoints rank points (numeric vector of length 4)
#' @param hongpai hongpai (numeric vector of length 3)
#' @param rongpai rongpai
#' @param zhuangfeng zhuangfeng (0-3)
#' @param menfeng menfeng (0-3)
#' @param lizhi lizhi (0-2)
#' @param yifa flag for "ippatsu"
#' @param qianggang flag for "chankan"
#' @param lingshang flag for "lingshang"
#' @param haidi haidi (0-2)
#' @param tianhu tianhu (0-2)
#' @param changbang changbang
#' @param lizhibang lizhibang
#' @returns A data frame
#' @keywords internal
skksph_get_defen <- function(paistr, baopai, libaopai, list, rankPoints, hongpai, rongpai = "", zhuangfeng = 0L, menfeng = 1L, lizhi = 0L, yifa = FALSE, qianggang = FALSE, lingshang = FALSE, haidi = 0L, tianhu = 0L, changbang = 0L, lizhibang = 0L) {
    .Call(`_shikakusphere_skksph_get_defen`, paistr, baopai, libaopai, list, rankPoints, hongpai, rongpai, zhuangfeng, menfeng, lizhi, yifa, qianggang, lingshang, haidi, tianhu, changbang, lizhibang)
}

#' Internal function to get xiangting number
#'
#' @param pai hand
#' @param index_s internal data (integer matrix)
#' @param index_h internal data (integer matrix)
#' @returns A data frame
#' @keywords internal
skksph_get_xiangting <- function(pai, index_s, index_h) {
    .Call(`_shikakusphere_skksph_get_xiangting`, pai, index_s, index_h)
}

#' Internal function to get tingpai
#'
#' @param pai hand
#' @param index_s internal data (integer matrix)
#' @param index_h internal data (integer matrix)
#' @returns A data frame
#' @keywords internal
skksph_get_tingpai <- function(pai, index_s, index_h) {
    .Call(`_shikakusphere_skksph_get_tingpai`, pai, index_s, index_h)
}

#' Internal function to convert bingpai to table
#'
#' @param pai hand
#' @returns A list of integer vectors
#' @keywords internal
skksph_bingpai_to_table <- function(pai) {
    .Call(`_shikakusphere_skksph_bingpai_to_table`, pai)
}

#' Internal function to get number of fulou mianzi
#'
#' @param pai hand
#' @returns An integer vector
#' @keywords internal
skksph_get_n_fulou <- function(pai) {
    .Call(`_shikakusphere_skksph_get_n_fulou`, pai)
}

#' Internal function to get pai features
#'
#' @param pai hand
#' @returns A list of numeric vectors
#' @keywords internal
skksph_feat_pai <- function(pai) {
    .Call(`_shikakusphere_skksph_feat_pai`, pai)
}

random_zhuangfeng <- function(n, zhuangfeng, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_zhuangfeng`, n, zhuangfeng, seed, list, rankPoints, hongpai)
}

random_menfeng <- function(n, menfeng, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_menfeng`, n, menfeng, seed, list, rankPoints, hongpai)
}

random_fanpai <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_fanpai`, n, seed, list, rankPoints, hongpai)
}

random_pinghe <- function(n, zhuangfeng, menfeng, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_pinghe`, n, zhuangfeng, menfeng, seed, list, rankPoints, hongpai)
}

random_duanyaojiu <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_duanyaojiu`, n, seed, list, rankPoints, hongpai)
}

random_yibeikou <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_yibeikou`, n, seed, list, rankPoints, hongpai)
}

random_sansetongshun <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_sansetongshun`, n, seed, list, rankPoints, hongpai)
}

random_yiqitongguan <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_yiqitongguan`, n, seed, list, rankPoints, hongpai)
}

random_hunquandaiyaojiu <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_hunquandaiyaojiu`, n, seed, list, rankPoints, hongpai)
}

random_qiduizi <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_qiduizi`, n, seed, list, rankPoints, hongpai)
}

random_duiduihu <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_duiduihu`, n, seed, list, rankPoints, hongpai)
}

random_sananke <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_sananke`, n, seed, list, rankPoints, hongpai)
}

random_sangangzi <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_sangangzi`, n, seed, list, rankPoints, hongpai)
}

random_sansetongke <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_sansetongke`, n, seed, list, rankPoints, hongpai)
}

random_hunlaotou <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_hunlaotou`, n, seed, list, rankPoints, hongpai)
}

random_xiaosanyuan <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_xiaosanyuan`, n, seed, list, rankPoints, hongpai)
}

random_hunyise <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_hunyise`, n, seed, list, rankPoints, hongpai)
}

random_chunquandaiyaojiu <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_chunquandaiyaojiu`, n, seed, list, rankPoints, hongpai)
}

random_erbeikou <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_erbeikou`, n, seed, list, rankPoints, hongpai)
}

random_qingyise <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_qingyise`, n, seed, list, rankPoints, hongpai)
}

random_guoshiwushuang <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_guoshiwushuang`, n, seed, list, rankPoints, hongpai)
}

random_sianke <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_sianke`, n, seed, list, rankPoints, hongpai)
}

random_dasanyuan <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_dasanyuan`, n, seed, list, rankPoints, hongpai)
}

random_xiaosixi <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_xiaosixi`, n, seed, list, rankPoints, hongpai)
}

random_dasixi <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_dasixi`, n, seed, list, rankPoints, hongpai)
}

random_ziyise <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_ziyise`, n, seed, list, rankPoints, hongpai)
}

random_lvyise <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_lvyise`, n, seed, list, rankPoints, hongpai)
}

random_qinglaotou <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_qinglaotou`, n, seed, list, rankPoints, hongpai)
}

random_sigangzi <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_sigangzi`, n, seed, list, rankPoints, hongpai)
}

random_jiulianbaodeng <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_jiulianbaodeng`, n, seed, list, rankPoints, hongpai)
}

