# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Internal function for `tidy(<skksph_paistr>)`
#'
#' @param pai Characters (hands).
#' @returns List of integers of length 36.
#' @noRd
skksph_tidy_impl <- function(pai) {
    .Call(`_shikakusphere_skksph_tidy_impl`, pai)
}

#' Internal function for `proceed()`
#'
#' @param qipai List of characters (tiles).
#' @param pai pai List of characters (tiles).
#' @param action action List of characters (tiles).
#' @param accumulate Logical. If true, returns accumulated result.
#' @returns Characters (hands).
#' @noRd
skksph_proceed_impl <- function(qipai, zimo, dapai, accumulate) {
    .Call(`_shikakusphere_skksph_proceed_impl`, qipai, zimo, dapai, accumulate)
}

#' Internal function for `lipai()`
#'
#' @param x List of a list of characters (tiles).
#' @returns Characters (hands).
#' @noRd
skksph_lipai_impl <- function(x) {
    .Call(`_shikakusphere_skksph_lipai_impl`, x)
}

#' Internal function to convert hands to SVG
#'
#' @param pai Characters (hands).
#' @returns Characters (SVG strings).
#' @noRd
skksph_hand_to_svg <- function(pai) {
    .Call(`_shikakusphere_skksph_hand_to_svg`, pai)
}

#' Internal function to get defen
#'
#' @param paistr String (hand)
#' @param baopai Characters (baopai)
#' @param libaopai Characters (libaopai)
#' @param list List (rule set)
#' @param rankPoints rank points (numerics of length 4)
#' @param hongpai hongpai (integers of length 3)
#' @param rongpai rongpai
#' @param zhuangfeng zhuangfeng (0-3)
#' @param menfeng menfeng (0-3)
#' @param lizhi lizhi (0-2)
#' @param yifa flag for "ippatsu"
#' @param qianggang flag for "chankan"
#' @param lingshang flag for "lingshang"
#' @param haidi haidi (0-2)
#' @param tianhu tianhu (0-2)
#' @param changbang changbang
#' @param lizhibang lizhibang
#' @returns Data frame
#' @noRd
skksph_get_defen <- function(paistr, baopai, libaopai, list, rankPoints, hongpai, rongpai = "", zhuangfeng = 0L, menfeng = 1L, lizhi = 0L, yifa = FALSE, qianggang = FALSE, lingshang = FALSE, haidi = 0L, tianhu = 0L, changbang = 0L, lizhibang = 0L) {
    .Call(`_shikakusphere_skksph_get_defen`, paistr, baopai, libaopai, list, rankPoints, hongpai, rongpai, zhuangfeng, menfeng, lizhi, yifa, qianggang, lingshang, haidi, tianhu, changbang, lizhibang)
}

#' Internal function to get xiangting number
#'
#' @param pai Characters (hands).
#' @param index_s Internal data (integer matrix).
#' @param index_h Internal data (integer matrix).
#' @returns Data frame.
#' @noRd
skksph_get_xiangting <- function(pai, index_s, index_h) {
    .Call(`_shikakusphere_skksph_get_xiangting`, pai, index_s, index_h)
}

#' Internal function to get tingpai
#'
#' @param pai Characters (hands).
#' @param index_s Internal data (integer matrix).
#' @param index_h Internal data (integer matrix).
#' @returns Data frame.
#' @noRd
skksph_get_tingpai <- function(pai, index_s, index_h) {
    .Call(`_shikakusphere_skksph_get_tingpai`, pai, index_s, index_h)
}

#' Internal function to convert bingpai to table
#'
#' @param pai Characters (hands).
#' @returns List of integers.
#' @noRd
skksph_bingpai_to_table <- function(pai) {
    .Call(`_shikakusphere_skksph_bingpai_to_table`, pai)
}

#' Internal function to get number of fulou mianzi
#'
#' @param pai Characters (hands).
#' @returns Integers.
#' @noRd
skksph_get_n_fulou <- function(pai) {
    .Call(`_shikakusphere_skksph_get_n_fulou`, pai)
}

skksph_rand_qipai_impl <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_skksph_rand_qipai_impl`, n, seed, list, rankPoints, hongpai)
}

random_zhuangfeng <- function(n, zhuangfeng, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_zhuangfeng`, n, zhuangfeng, seed, list, rankPoints, hongpai)
}

random_menfeng <- function(n, menfeng, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_menfeng`, n, menfeng, seed, list, rankPoints, hongpai)
}

random_fanpai <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_fanpai`, n, seed, list, rankPoints, hongpai)
}

random_pinghe <- function(n, zhuangfeng, menfeng, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_pinghe`, n, zhuangfeng, menfeng, seed, list, rankPoints, hongpai)
}

random_duanyaojiu <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_duanyaojiu`, n, seed, list, rankPoints, hongpai)
}

random_yibeikou <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_yibeikou`, n, seed, list, rankPoints, hongpai)
}

random_sansetongshun <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_sansetongshun`, n, seed, list, rankPoints, hongpai)
}

random_yiqitongguan <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_yiqitongguan`, n, seed, list, rankPoints, hongpai)
}

random_hunquandaiyaojiu <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_hunquandaiyaojiu`, n, seed, list, rankPoints, hongpai)
}

random_qiduizi <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_qiduizi`, n, seed, list, rankPoints, hongpai)
}

random_duiduihu <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_duiduihu`, n, seed, list, rankPoints, hongpai)
}

random_sananke <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_sananke`, n, seed, list, rankPoints, hongpai)
}

random_sangangzi <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_sangangzi`, n, seed, list, rankPoints, hongpai)
}

random_sansetongke <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_sansetongke`, n, seed, list, rankPoints, hongpai)
}

random_hunlaotou <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_hunlaotou`, n, seed, list, rankPoints, hongpai)
}

random_xiaosanyuan <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_xiaosanyuan`, n, seed, list, rankPoints, hongpai)
}

random_hunyise <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_hunyise`, n, seed, list, rankPoints, hongpai)
}

random_chunquandaiyaojiu <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_chunquandaiyaojiu`, n, seed, list, rankPoints, hongpai)
}

random_erbeikou <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_erbeikou`, n, seed, list, rankPoints, hongpai)
}

random_qingyise <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_qingyise`, n, seed, list, rankPoints, hongpai)
}

random_guoshiwushuang <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_guoshiwushuang`, n, seed, list, rankPoints, hongpai)
}

random_sianke <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_sianke`, n, seed, list, rankPoints, hongpai)
}

random_dasanyuan <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_dasanyuan`, n, seed, list, rankPoints, hongpai)
}

random_xiaosixi <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_xiaosixi`, n, seed, list, rankPoints, hongpai)
}

random_dasixi <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_dasixi`, n, seed, list, rankPoints, hongpai)
}

random_ziyise <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_ziyise`, n, seed, list, rankPoints, hongpai)
}

random_lvyise <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_lvyise`, n, seed, list, rankPoints, hongpai)
}

random_qinglaotou <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_qinglaotou`, n, seed, list, rankPoints, hongpai)
}

random_sigangzi <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_sigangzi`, n, seed, list, rankPoints, hongpai)
}

random_jiulianbaodeng <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_jiulianbaodeng`, n, seed, list, rankPoints, hongpai)
}

