# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

skksph_shoupai_to_svg <- function(pai) {
    .Call(`_shikakusphere_skksph_shoupai_to_svg`, pai)
}

skksph_get_defen <- function(paistr, baopai, libaopai, list, rankPoints, hongpai, rongpai = "", zhuangfeng = 0L, menfeng = 1L, lizhi = 0L, yifa = FALSE, qianggang = FALSE, lingshang = FALSE, haidi = 0L, tianhu = 0L, changbang = 0L, lizhibang = 0L) {
    .Call(`_shikakusphere_skksph_get_defen`, paistr, baopai, libaopai, list, rankPoints, hongpai, rongpai, zhuangfeng, menfeng, lizhi, yifa, qianggang, lingshang, haidi, tianhu, changbang, lizhibang)
}

skksph_get_xiangting <- function(shoupai) {
    .Call(`_shikakusphere_skksph_get_xiangting`, shoupai)
}

skksph_get_tingpai <- function(shoupai) {
    .Call(`_shikakusphere_skksph_get_tingpai`, shoupai)
}

random_zhuangfeng <- function(n, zhuangfeng, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_zhuangfeng`, n, zhuangfeng, seed, list, rankPoints, hongpai)
}

random_menfeng <- function(n, menfeng, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_menfeng`, n, menfeng, seed, list, rankPoints, hongpai)
}

random_fanpai <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_fanpai`, n, seed, list, rankPoints, hongpai)
}

random_pinghe <- function(n, zhuangfeng, menfeng, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_pinghe`, n, zhuangfeng, menfeng, seed, list, rankPoints, hongpai)
}

random_duanyaojiu <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_duanyaojiu`, n, seed, list, rankPoints, hongpai)
}

random_yibeikou <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_yibeikou`, n, seed, list, rankPoints, hongpai)
}

random_sansetongshun <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_sansetongshun`, n, seed, list, rankPoints, hongpai)
}

random_yiqitongguan <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_yiqitongguan`, n, seed, list, rankPoints, hongpai)
}

random_hunquandaiyaojiu <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_hunquandaiyaojiu`, n, seed, list, rankPoints, hongpai)
}

random_qiduizi <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_qiduizi`, n, seed, list, rankPoints, hongpai)
}

random_duiduihu <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_duiduihu`, n, seed, list, rankPoints, hongpai)
}

random_sananke <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_sananke`, n, seed, list, rankPoints, hongpai)
}

random_sangangzi <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_sangangzi`, n, seed, list, rankPoints, hongpai)
}

random_sansetongke <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_sansetongke`, n, seed, list, rankPoints, hongpai)
}

random_hunlaotou <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_hunlaotou`, n, seed, list, rankPoints, hongpai)
}

random_xiaosanyuan <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_xiaosanyuan`, n, seed, list, rankPoints, hongpai)
}

random_hunyise <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_hunyise`, n, seed, list, rankPoints, hongpai)
}

random_chunquandaiyaojiu <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_chunquandaiyaojiu`, n, seed, list, rankPoints, hongpai)
}

random_erbeikou <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_erbeikou`, n, seed, list, rankPoints, hongpai)
}

random_qingyise <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_qingyise`, n, seed, list, rankPoints, hongpai)
}

random_guoshiwushuang <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_guoshiwushuang`, n, seed, list, rankPoints, hongpai)
}

random_sianke <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_sianke`, n, seed, list, rankPoints, hongpai)
}

random_dasanyuan <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_dasanyuan`, n, seed, list, rankPoints, hongpai)
}

random_xiaosixi <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_xiaosixi`, n, seed, list, rankPoints, hongpai)
}

random_dasixi <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_dasixi`, n, seed, list, rankPoints, hongpai)
}

random_ziyise <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_ziyise`, n, seed, list, rankPoints, hongpai)
}

random_lvyise <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_lvyise`, n, seed, list, rankPoints, hongpai)
}

random_qinglaotou <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_qinglaotou`, n, seed, list, rankPoints, hongpai)
}

random_sigangzi <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_sigangzi`, n, seed, list, rankPoints, hongpai)
}

random_jiulianbaodeng <- function(n, seed, list, rankPoints, hongpai) {
    .Call(`_shikakusphere_random_jiulianbaodeng`, n, seed, list, rankPoints, hongpai)
}

